sudo: false
language: python
python:
  - "2.7"

# services:
#     - rabbitmq

addons:
  apt_packages:
    - libenchant-dev

cache:
  directories:
    - $HOME/.cache/pip

script:
  - python2 ./setup.py test
